remote: true
hybrid: true
onsite: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software engineer

# One or more keywords to look for in the job description, for example, "chromium browser". This field is optional.
# Only use this field to find jobs that require specific technologies, products, or skills that is not mentioned in the job title.
# Warning: Any jobs without matching keywords in the job description will be skipped.
job_description_keywords_whitelist:  

locations:
  - Germany

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
