remote: true

experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: false
 24 hours: true

positions:
  - Marketing Manager
  - Product Marketing

locations:
  - Spain
  - England

distance: 100

companyBlacklist:
  - Bajaj Auto
  - Bajaj
  - EPAM
  - Motion Recruitment

titleBlacklist:
  - Technical
  - Sales
  - Business Development
  - Developer
  - Tester
  - Engineer
