remote: [true]

experienceLevel:
 internship: [false]
 entry: [false]
 associate: [true]
 mid-senior level: [false]
 director: [false]
 executive: [false]

jobTypes:
 full-time: [true]
 contract: [true]
 part-time: [false]
 temporary: [false]
 internship: [false]
 other: [false]
 volunteer: [false]

date:
 all time: [false]
 month: [false]
 week: [true]
 24 hours: [false]

positions:
  - Software Engineer
  - Site Reliability Engineer
  - Full Stack Developer
  - Web Application Developer
  - React Web Developer
  - Web Developer
  - NodeJS Developer
  - DevOps Engineer

locations:
  - Dallas, Texas
  - Houston, Tx
  
distance: 50

companyBlacklist:
  - RealPage
  - Company2

titleBlacklist:
  - Sales
  - Marketing
