remote: false

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Software engineer
  - Devops engineer
  - SRE engineer
  - Software Developer
  - Python Develoepr
  - Software engineer (Python)
  - Software Developer (python)

locations:
  - US
  - United States
  - California
  - Bay Area
  - Los Angeles
  - Seattle
  - Oregon

apply_once_at_company: true

distance: 100

company_blacklist:


title_blacklist:
  - Citizen only
  - Visa Required
  - Security Clearance
  - No Visa
  - No Sponsorship

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 1000

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
