remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: true
 internship: false
 other: true
 volunteer: false

date:
 all time: true
 month: true
 week: true
 24 hours: true

positions:
  - Full Stack Developer
  - Javascript Developer
  - Python Developer
  - Web Developer
  - Software Developer
  - Software Engineer
  - Backend Developer
  - Frontend Developer
  - React Native Developer
  - Node.js Developer
  - C++ Developer
  - Go Developer

locations:
  - USA
  - United States
  - Switzerland
  - Australia
  - Germany
  - Canada
  - United Kingdom
  - Netherlands
  - Sweden
  - Ireland
  - France
  - United Arab Emirates
  - Saudi Arabia
  - Qatar
  - Kuwait
  - Oman
  - Bahrain
  - Poland
  - India
  - Brazil
  - South Africa
  - Philippines
  - Egypt
  - Jordan
  - Lebanon
  - Morocco
  - Tunisia
  - Spain
  - Italy
  - Denmark
  - Finland
  - Norway
  - Belgium
  - Austria
  - New Zealand
  - Singapore
  - Japan
  - South Korea
  - Mexico
  - Argentina
  - Chile
  - Turkey
  - Malaysia
  - Indonesia
  - Vietnam
  - Pakistan
  - Nigeria
  - Kenya
  - Ukraine
  - Thailand
  - Costa Rica


distance: 0

companyBlacklist: []

titleBlacklist: []