remote: [true/false]

experienceLevel:
 internship: [true/false]
 entry: [true/false]
 associate: [true/false]
 mid-senior level: [true/false]
 director: [true/false]
 executive: [true/false]

jobTypes:
 full-time: [true/false]
 contract: [true/false]
 part-time: [true/false]
 temporary: [true/false]
 internship: [true/false]
 other: [true/false]
 volunteer: [true/false]

date:
 all time: [true/false]
 month: [true/false]
 week: [true/false]
 24 hours: [true/false]

positions:
  - position1
  - position2

locations:
  - Country1
  - Country2

applyOnceAtCompany: [true/false]

distance: 100

company_blacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 100
  
llm_model_type: openai
llm_model: gpt-4o 
llm_api_url: https://api.pawan.krd/cosmosrp/v1