---
remote: true

experienceLevel:
 internship: false
 entry: false
 associate: false
 mid-senior level: true
 director: true
 executive: true

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: true
 internship: false
 other: true
 volunteer: false

date:
 all time: true
 month: false
 week: false
 24 hours: false

positions:
 - Head of Machine Learning
 - Machine Learning Engineer
 - Machine Learning Scientist
 - Machine Learning Researcher
 - Generative AI
 - GenAI
 - ML Engineer
 - Senior ML Engineer

locations:
 - France
 - Germany
 - United Kingdom
 - United States
 - Canada
 - Australia
 - New Zealand
 - Singapore
 - Japan
 - South Korea
 - China
 - Switzerland
 - Sweden
 - Norway
 - Denmark
 - Finland
 - Netherlands
 - Belgium
 - Luxembourg
 - Austria
 - Ireland
 - Spain
 - Portugal
 - Italy

distance: 100

companyBlacklist:
 - Company1
 - Company2

titleBlacklist:
 - word1
 - word2
